apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-web
spec:
  selector:
    matchLabels:
      app: nginx-web
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: pda-nginx
        image: jvision1/nginx-web
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
